export enum ApiResponseCode {
  HEALTH_CHECK_OK = 'HEALTH_CHECK_OK',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  AUTHENTICATION_UNAUTHORIZED = 'AUTHENTICATION_UNAUTHORIZED',
  AUTHENTICATION_NO_JWT_SECRET = 'AUTHENTICATION_NO_JWT_SECRET',

  ACTION_FORBIDDEN = 'ACTION_FORBIDDEN',

  APPLICATIONS_SUBMITTED = 'APPLICATIONS_SUBMITTED',
  APPLICATIONS_STATUS_UPDATED = 'APPLICATIONS_STATUS_UPDATED',
  APPLICATIONS_JOB_OFFER_FOUND = 'APPLICATIONS_JOB_OFFER_FOUND',
  APPLICATIONS_IMAM_FOUND = 'APPLICATIONS_IMAM_FOUND',
  APPLICATIONS_IMAM_HAS_ALREADY_APPLIED_TO_THIS_JOB_OFFER = 'APPLICATIONS_IMAM_HAS_ALREADY_APPLIED_TO_THIS_JOB_OFFER',
  APPLICATIONS_NOT_FOUND = 'APPLICATIONS_NOT_FOUND',
}
